packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

variable "github_token" {
  type = string
}

variable "instance_type" {
  type    = string
  default = "c5.large"
}

variable "region" {
  type    = string
  default = "ap-south-1"
}

variable "repository" {
  type    = string
  default = "pb-admin1/WT-CMS.git"
}

variable "ssh_username" {
  type    = string
  default = "ubuntu"
}

variable "vpc_id" {
  type    = string
  default = "vpc-0708622df34ce2620"
}

variable "subnet_id" {
  type    = string
  default = "subnet-0e2eaf6fc179b7347"
}

variable "volume_size" {
  type    = number
  default = 20
}

variable "volume_type" {
  type    = string
  default = "gp3"
}

variable "environment" {
  type    = string
  default = "sandbox"
}
variable "branch" {
  type    = string
  default = "master"
}

variable "env_wt_admin" {
  type = string
  description = "Config file content from GitHub secrets"
  sensitive = true
  default = ""
}

source "amazon-ebs" "autogenerated_1" {

  ami_name = "${var.environment == "production" ? "PB-WT-ADMIN-PROD" : "SB-WT-ADMIN-SANDBOX"}-${formatdate("YYYY-MM-DD-hhmmss", timestamp())}"

  instance_type         = var.instance_type
  region                = var.region
  source_ami            = var.environment == "production" ? "ami-0e5374f6c190b3f1b" : "ami-08671723e045de2ab"
  ssh_username          = var.ssh_username
  vpc_id                = var.vpc_id
  subnet_id             = var.subnet_id
  

  launch_block_device_mappings {
        device_name = "/dev/sda1"
        volume_size = 20
        volume_type = "gp3"
       delete_on_termination = true
    }
  tags = {
    #Name = "PB-CMS_PROD"
    Name = "${var.environment == "production" ? "PB-WT-ADMIN-" : "SB-WT-ADMIN"}"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    inline = [
      "sudo rm -rf /var/www/html/*",
      "if [ -d /var/www/html ]; then sudo rm -rf /var/www/html; fi",
      "sudo mkdir -p /var/www/html",
      "sudo git config --global credential.helper 'cache --timeout=3600'",
      "sudo echo \"https://hariomsing29:${var.github_token}@github.com\" > ~/.git-credentials",
      "sudo git clone --branch ${var.branch} https://hariomsing29:${var.github_token}@github.com/pb-admin1/WT-CMS.git /var/www/html/"
    ]
  }

provisioner "file" {
  content = var.env_wt_admin
  destination = "/tmp/.env"
}


provisioner "shell" {
  inline = [
    "set -e",
    "cd /var/www/html",
    "sudo mv /tmp/.env /var/www/html/",
    "sudo chown -R ubuntu:ubuntu /var/www/html",
    "sudo chmod -R u+w /var/www/html",
    "sudo rm -rf /var/www/html/.git /var/www/html/.github /var/www/html/.gitignore",
    "composer install --no-dev --optimize-autoloader -n",
    "npm install",
    "npm run build",
    "php artisan cache:clear",
    "php artisan route:clear",
    "php artisan view:clear",
    "php artisan optimize:clear",
    "php artisan config:cache",
    "sudo chown -R www-data:www-data /var/www/html",
    "sudo chmod -R 755 /var/www/html"
  ]
}



  # Cleanup provisioner to remove Git credentials
  provisioner "shell" {
    inline = [
      "sudo rm -f ~/.git-credentials",
      "sudo git config --global --unset credential.helper"
    ]
  }
}
